# Generated by Django 3.0.5 on 2020-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='face',
            field=models.ImageField(null=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='sex',
            field=models.BooleanField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
    ]
