# Generated by Django 3.0.5 on 2020-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200417_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片'),
        ),
    ]
