# Generated by Django 3.0.5 on 2020-04-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200417_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='email',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
    ]
