# Generated by Django 3.0.5 on 2020-04-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200418_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
